In [1]:
# Versão da Linguagem Python
from platform import python_version
print('Versão da Linguagem Python Usada Neste Jupyter Notebook:', python_version())

Versão da Linguagem Python Usada Neste Jupyter Notebook: 3.12.3


In [2]:
# Importando o NumPy
import numpy as np

In [3]:
np.__version__

'1.26.4'

In [4]:
# Instrução para instalar uma versão exata do pacote em Python
# !pip install numpy==1.22.2

### Criando Arrays NumPy

In [5]:
# Array criado a partir de uma lista Python
arr1 = np.array([10, 21, 32, 43, 48, 15, 76, 57, 89])

In [6]:
print(arr1)

[10 21 32 43 48 15 76 57 89]


In [7]:
# Um objeto do tipo ndarray é um recipiente multidimensional de itens do mesmo tipo e tamanho
type(arr1)

numpy.ndarray

In [8]:
# Verificando o formato do array
arr1.shape

(9,)

Um array NumPy é uma estrutura de dados multidimensional usada em computação científica e análise de dados. O NumPy fornece um objeto de matriz N-dimensional (ou ndarray), que é uma grade homogênea de elementos, geralmente números, que podem ser indexados por um conjunto de inteiros.

Os arrays NumPy são mais eficientes do que as listas Python para armazenar e manipular grandes quantidades de dados, pois são implementados em Linguagem C e fornecem várias otimizações de desempenho. Além disso, o NumPy permite a fácil leitura e escrita de arquivos de dados, integração com outras bibliotecas Python e suporte a operações em paralelo usando várias CPUs ou GPUs.

### Indexação em Arrays NumPy

In [9]:
print(arr1)

[10 21 32 43 48 15 76 57 89]


In [10]:
# Imprimindo um elemento específico no array
arr1[4]

48

In [11]:
# Indexação
arr1[1:4] 

array([21, 32, 43])

In [12]:
# Indexação
arr1[1:4+1]

array([21, 32, 43, 48])

In [13]:
# Cria uma lista de índices
indices = [1, 2, 5, 6]

In [14]:
# Imprimindo os elementos dos índices
arr1[indices] 

array([21, 32, 15, 76])

In [15]:
# Cria uma máscara booleana para os elementos pares
mask = (arr1 % 2 == 0)

In [16]:
mask

array([ True, False,  True, False,  True, False,  True, False, False])

In [17]:
arr1[mask]

array([10, 32, 48, 76])

In [18]:
# Alterando um elemento do array
arr1[0] = 100

In [19]:
print(arr1)

[100  21  32  43  48  15  76  57  89]


In [20]:
# Não é possível incluir elemento de outro tipo
try:
    arr1[0] = 'Novo elemento'
except:
    print("Operação não permitida!")

Operação não permitida!


### Funções NumPy

In [21]:
# A função array() cria um array NumPy
arr2 = np.array([1, 2, 3, 4, 5])

In [22]:
print(arr2)

[1 2 3 4 5]


In [23]:
# Verificando o tipo do objeto
type(arr2)

numpy.ndarray

In [24]:
# Digite . e pressione a tecla Tab no seu teclado para visualizar os métodos disponíveis em objetos NumPy
arr2

array([1, 2, 3, 4, 5])

In [25]:
# Usando métodos do array NumPy
arr2.cumsum()

array([ 1,  3,  6, 10, 15])

In [26]:
arr2.cumprod()

array([  1,   2,   6,  24, 120])

In [27]:
# Digite . e pressione a tecla Tab no seu teclado para visualizar as funções para manipular objetos NumPy
np

<module 'numpy' from 'c:\\Users\\samue\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\numpy\\__init__.py'>

In [28]:
# A função arange cria um array NumPy contendo uma progressão aritmética a partir de um intervalo - start, stop, step
arr3 = np.arange(0, 50, 5)

In [29]:
print(arr3)

[ 0  5 10 15 20 25 30 35 40 45]


In [30]:
# Verificando o tipo do objeto
type(arr3)

numpy.ndarray

In [31]:
# Formato do array
np.shape(arr3)

(10,)

In [32]:
print(arr3.dtype)

int32


In [33]:
# Cria um array preenchido com zeros
arr4 = np.zeros(10)

In [34]:
print(arr4)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [35]:
# Retorna 1 nas posições em diagonal e 0 no restante
arr5 = np.eye(3)

In [36]:
print(arr5)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [37]:
# Os valores passados como parâmetro, formam uma diagonal
arr6 = np.diag(np.array([1, 2, 3, 4]))

In [38]:
print(arr6)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


In [39]:
# Array de valores booleanos
arr7 = np.array([True, False, False, True])

In [40]:
print(arr7)

[ True False False  True]


In [41]:
# Array de strings
arr8 = np.array(['Linguagem Python', 'Linguagem R', 'Linguagem Julia'])

In [42]:
print(arr8)

['Linguagem Python' 'Linguagem R' 'Linguagem Julia']


In [43]:
print(np.linspace(0, 10))

[ 0.          0.20408163  0.40816327  0.6122449   0.81632653  1.02040816
  1.2244898   1.42857143  1.63265306  1.83673469  2.04081633  2.24489796
  2.44897959  2.65306122  2.85714286  3.06122449  3.26530612  3.46938776
  3.67346939  3.87755102  4.08163265  4.28571429  4.48979592  4.69387755
  4.89795918  5.10204082  5.30612245  5.51020408  5.71428571  5.91836735
  6.12244898  6.32653061  6.53061224  6.73469388  6.93877551  7.14285714
  7.34693878  7.55102041  7.75510204  7.95918367  8.16326531  8.36734694
  8.57142857  8.7755102   8.97959184  9.18367347  9.3877551   9.59183673
  9.79591837 10.        ]


In [44]:
print(np.linspace(0, 10, 15))

[ 0.          0.71428571  1.42857143  2.14285714  2.85714286  3.57142857
  4.28571429  5.          5.71428571  6.42857143  7.14285714  7.85714286
  8.57142857  9.28571429 10.        ]


In [45]:
print(np.logspace(0, 5, 10))

[1.00000000e+00 3.59381366e+00 1.29154967e+01 4.64158883e+01
 1.66810054e+02 5.99484250e+02 2.15443469e+03 7.74263683e+03
 2.78255940e+04 1.00000000e+05]


### Manipulando Matrizes

In [46]:
# Criando uma matriz
arr9 = np.array( [ [1,2,3] , [4,5,6] ] ) 

In [47]:
type(arr9)

numpy.ndarray

In [48]:
print(arr9)

[[1 2 3]
 [4 5 6]]


In [49]:
print(arr9.shape)

(2, 3)


In [50]:
# Criando uma matriz 2x3 apenas com números "1"
arr10 = np.ones((2,3))

In [51]:
print(arr10)

[[1. 1. 1.]
 [1. 1. 1.]]


In [52]:
# Lista de listas
lista = [[13,81,22], [0, 34, 59], [21, 48, 94]]

In [53]:
# A função matrix cria uma matriz a partir de uma lista de listas
arr11 = np.matrix(lista)

In [54]:
type(arr11)

numpy.matrix

In [55]:
print(arr11)

[[13 81 22]
 [ 0 34 59]
 [21 48 94]]


In [56]:
# Formato da matriz
np.shape(arr11)

(3, 3)

In [57]:
# Tamanho da matriz
arr11.size

9

In [58]:
print(arr11.dtype)

int32


In [59]:
print(arr11)

[[13 81 22]
 [ 0 34 59]
 [21 48 94]]


In [60]:
# Indexação da matriz
arr11[2,1]

48

In [61]:
# Indexação da matriz
arr11[0:2,2]

matrix([[22],
        [59]])

In [62]:
# Indexação da matriz
arr11[1,]

matrix([[ 0, 34, 59]])

In [63]:
# Alterando um elemento da matriz
arr11[1,0] = 100

In [64]:
print(arr11)

[[ 13  81  22]
 [100  34  59]
 [ 21  48  94]]


In [65]:
x = np.array([1, 2])  # NumPy decide o tipo dos dado
y = np.array([1.0, 2.0])  # NumPy decide o tipo dos dado
z = np.array([1, 2], dtype = np.float64)  # Forçamos um tipo de dado em particular

In [66]:
print(x.dtype, y.dtype, z.dtype)

int32 float64 float64


In [67]:
arr12 = np.array([[24, 76, 92, 14], [47, 35, 89, 2]], dtype = float)

In [68]:
print(arr12)

[[24. 76. 92. 14.]
 [47. 35. 89.  2.]]


In [69]:
arr12.itemsize

8

In [70]:
arr12.nbytes

64

In [71]:
arr12.ndim

2

### Manipulando Objetos de 3 e 4 Dimensões com NumPy

In [72]:
# Cria um array numpy de 3 dimensões
arr_3d = np.array([
    [
        [1, 2, 3, 4],
        [5, 6, 7, 8],
        [9, 10, 11, 12]
    ],
    [
        [13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]
    ]
])

In [73]:
print(arr_3d)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]


In [74]:
arr_3d.ndim

3

In [75]:
arr_3d.shape

(2, 3, 4)

In [76]:
arr_3d[0, 2, 1]

10

In [77]:
# Cria um array numpy de 4 dimensões
arr_4d = np.array([
    [
        [
            [1, 2, 3, 4, 5],
            [6, 7, 8, 9, 10],
            [11, 12, 13, 14, 15],
            [16, 17, 18, 19, 20]
        ],
        [
            [21, 22, 23, 24, 25],
            [26, 27, 28, 29, 30],
            [31, 32, 33, 34, 35],
            [36, 37, 38, 39, 40]
        ],
        [
            [41, 42, 43, 44, 45],
            [46, 47, 48, 49, 50],
            [51, 52, 53, 54, 55],
            [56, 57, 58, 59, 60]
        ]
    ],
    [
        [
            [61, 62, 63, 64, 65],
            [66, 67, 68, 69, 70],
            [71, 72, 73, 74, 75],
            [76, 77, 78, 79, 80]
        ],
        [
            [81, 82, 83, 84, 85],
            [86, 87, 88, 89, 90],
            [91, 92, 93, 94, 95],
            [96, 97, 98, 99, 100]
        ],
        [
            [101, 102, 103, 104, 105],
            [106, 107, 108, 109, 110],
            [111, 112, 113, 114, 115],
            [116, 117, 118, 119, 120]
        ]
    ]
])