In [1]:
# Versão da Linguagem Python
from platform import python_version
print('Versão da Linguagem Python Usada Neste Jupyter Notebook:', python_version())

Versão da Linguagem Python Usada Neste Jupyter Notebook: 3.12.3


In [2]:
# Importando o NumPy
import numpy as np

In [3]:
np.__version__

'1.26.4'

In [4]:
# Instrução para instalar uma versão exata do pacote em Python
# !pip install numpy==1.22.2

### Criando Arrays NumPy

In [5]:
# Array criado a partir de uma lista Python
arr1 = np.array([10, 21, 32, 43, 48, 15, 76, 57, 89])

In [6]:
print(arr1)

[10 21 32 43 48 15 76 57 89]


In [7]:
# Um objeto do tipo ndarray é um recipiente multidimensional de itens do mesmo tipo e tamanho
type(arr1)

numpy.ndarray

In [8]:
# Verificando o formato do array
arr1.shape

(9,)

Um array NumPy é uma estrutura de dados multidimensional usada em computação científica e análise de dados. O NumPy fornece um objeto de matriz N-dimensional (ou ndarray), que é uma grade homogênea de elementos, geralmente números, que podem ser indexados por um conjunto de inteiros.

Os arrays NumPy são mais eficientes do que as listas Python para armazenar e manipular grandes quantidades de dados, pois são implementados em Linguagem C e fornecem várias otimizações de desempenho. Além disso, o NumPy permite a fácil leitura e escrita de arquivos de dados, integração com outras bibliotecas Python e suporte a operações em paralelo usando várias CPUs ou GPUs.

### Indexação em Arrays NumPy

In [9]:
print(arr1)

[10 21 32 43 48 15 76 57 89]


In [10]:
# Imprimindo um elemento específico no array
arr1[4]

48

In [11]:
# Indexação
arr1[1:4] 

array([21, 32, 43])

In [12]:
# Indexação
arr1[1:4+1]

array([21, 32, 43, 48])

In [13]:
# Cria uma lista de índices
indices = [1, 2, 5, 6]

In [14]:
# Imprimindo os elementos dos índices
arr1[indices] 

array([21, 32, 15, 76])

In [15]:
# Cria uma máscara booleana para os elementos pares
mask = (arr1 % 2 == 0)

In [16]:
mask

array([ True, False,  True, False,  True, False,  True, False, False])

In [17]:
arr1[mask]

array([10, 32, 48, 76])

In [18]:
# Alterando um elemento do array
arr1[0] = 100